
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 21;
  public static final int COM_NOT_EQUAL = 44;
  public static final int POW = 16;
  public static final int MAIN_FUNC = 47;
  public static final int MULT = 8;
  public static final int CHAR = 15;
  public static final int LPAREN_TRI = 29;
  public static final int INTEGER = 2;
  public static final int LPAREN = 25;
  public static final int BADCHAR = 33;
  public static final int INT = 10;
  public static final int MINUS = 7;
  public static final int LPAREN_CURLY = 27;
  public static final int CHARACTER = 35;
  public static final int RPAREN = 26;
  public static final int LESS_THAN_OR_EQ = 46;
  public static final int LPAREN_SQ = 31;
  public static final int RATIONAL = 37;
  public static final int BOOL = 12;
  public static final int COMMA = 18;
  public static final int SEMICOL = 5;
  public static final int FI = 39;
  public static final int DIV = 9;
  public static final int RPAREN_TRI = 30;
  public static final int RAT = 14;
  public static final int PLUS = 6;
  public static final int IF = 38;
  public static final int QUOTE = 23;
  public static final int COM_EQUAL = 43;
  public static final int FLOATING = 36;
  public static final int RPAREN_CURLY = 28;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int EQUAL = 4;
  public static final int error = 1;
  public static final int BREAK = 41;
  public static final int SINGLE_QUOTE = 24;
  public static final int TOP = 13;
  public static final int COL = 19;
  public static final int ELSE = 40;
  public static final int DICT = 17;
  public static final int METHOD_DECLARATOR = 48;
  public static final int FLOAT = 11;
  public static final int THEN = 42;
  public static final int RPAREN_SQ = 32;
  public static final int ALIAS = 22;
  public static final int LESS_THAN = 45;
  public static final int INTEGER_LITERAL = 34;
  public static final int IDENTIFIER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "IDENTIFIER",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "INT",
  "FLOAT",
  "BOOL",
  "TOP",
  "RAT",
  "CHAR",
  "POW",
  "DICT",
  "COMMA",
  "COL",
  "RETURN",
  "SEQ",
  "ALIAS",
  "QUOTE",
  "SINGLE_QUOTE",
  "LPAREN",
  "RPAREN",
  "LPAREN_CURLY",
  "RPAREN_CURLY",
  "LPAREN_TRI",
  "RPAREN_TRI",
  "LPAREN_SQ",
  "RPAREN_SQ",
  "BADCHAR",
  "INTEGER_LITERAL",
  "CHARACTER",
  "FLOATING",
  "RATIONAL",
  "IF",
  "FI",
  "ELSE",
  "BREAK",
  "THEN",
  "COM_EQUAL",
  "COM_NOT_EQUAL",
  "LESS_THAN",
  "LESS_THAN_OR_EQ",
  "MAIN_FUNC",
  "METHOD_DECLARATOR"
  };
}

