
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 25;
  public static final int COM_NOT_EQUAL = 57;
  public static final int POW = 20;
  public static final int STRING_LITERAL = 34;
  public static final int MAIN_FUNC = 62;
  public static final int MULT = 8;
  public static final int CHAR = 19;
  public static final int POOL = 61;
  public static final int LPAREN_TRI = 40;
  public static final int INTEGER = 2;
  public static final int LPAREN = 36;
  public static final int BADCHAR = 44;
  public static final int INT = 10;
  public static final int MINUS = 7;
  public static final int LPAREN_CURLY = 38;
  public static final int CHARACTER = 46;
  public static final int RPAREN = 37;
  public static final int LESS_THAN_OR_EQ = 59;
  public static final int LPAREN_SQ = 42;
  public static final int NOT = 29;
  public static final int AND = 30;
  public static final int RATIONAL = 48;
  public static final int OR = 31;
  public static final int BOOL = 12;
  public static final int COMMA = 22;
  public static final int SEMICOL = 5;
  public static final int FI = 52;
  public static final int RPAREN_TRI = 41;
  public static final int DIV = 9;
  public static final int TYPE_DECLARATOR = 64;
  public static final int RAT = 18;
  public static final int LOOP = 60;
  public static final int PLUS = 6;
  public static final int IF = 51;
  public static final int QUOTE = 27;
  public static final int COM_EQUAL = 56;
  public static final int DOT = 14;
  public static final int FLOATING = 47;
  public static final int RPAREN_CURLY = 39;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int EQUAL = 4;
  public static final int TRUE = 49;
  public static final int error = 1;
  public static final int NULL = 17;
  public static final int BREAK = 54;
  public static final int IMPLY = 33;
  public static final int SINGLE_QUOTE = 28;
  public static final int TOP = 13;
  public static final int COL = 23;
  public static final int ELSE = 53;
  public static final int DICT = 21;
  public static final int METHOD_DECLARATOR = 63;
  public static final int FLOAT = 11;
  public static final int THEN = 55;
  public static final int RPAREN_SQ = 43;
  public static final int LEN = 15;
  public static final int STRING = 16;
  public static final int QUESTION = 32;
  public static final int ALIAS = 26;
  public static final int FALSE = 50;
  public static final int LESS_THAN = 58;
  public static final int PRINT = 35;
  public static final int INTEGER_LITERAL = 45;
  public static final int IDENTIFIER = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "IDENTIFIER",
  "EQUAL",
  "SEMICOL",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "INT",
  "FLOAT",
  "BOOL",
  "TOP",
  "DOT",
  "LEN",
  "STRING",
  "NULL",
  "RAT",
  "CHAR",
  "POW",
  "DICT",
  "COMMA",
  "COL",
  "RETURN",
  "SEQ",
  "ALIAS",
  "QUOTE",
  "SINGLE_QUOTE",
  "NOT",
  "AND",
  "OR",
  "QUESTION",
  "IMPLY",
  "STRING_LITERAL",
  "PRINT",
  "LPAREN",
  "RPAREN",
  "LPAREN_CURLY",
  "RPAREN_CURLY",
  "LPAREN_TRI",
  "RPAREN_TRI",
  "LPAREN_SQ",
  "RPAREN_SQ",
  "BADCHAR",
  "INTEGER_LITERAL",
  "CHARACTER",
  "FLOATING",
  "RATIONAL",
  "TRUE",
  "FALSE",
  "IF",
  "FI",
  "ELSE",
  "BREAK",
  "THEN",
  "COM_EQUAL",
  "COM_NOT_EQUAL",
  "LESS_THAN",
  "LESS_THAN_OR_EQ",
  "LOOP",
  "POOL",
  "MAIN_FUNC",
  "METHOD_DECLARATOR",
  "TYPE_DECLARATOR"
  };
}

